// <auto-generated />
using System;
using GmailManager.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GmailManager.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260514095012_AddNotificationsTable")]
    partial class AddNotificationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GmailManager.Shared.Entities.BulkEmailJobEntity", b =>
                {
                    b.Property<string>("JobId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("JobId"), "ascii");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DelaySeconds")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("longtext");

                    b.Property<int>("FailureCount")
                        .HasColumnType("int");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("int");

                    b.Property<string>("RecipientsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("JobId");

                    b.ToTable("BulkEmailJobs");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.CampaignEntity", b =>
                {
                    b.Property<string>("CampaignId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CampaignId"), "ascii");

                    b.Property<decimal?>("CampaignCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ListId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ListId"), "ascii");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("ScheduledAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SegmentId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SegmentId"), "ascii");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Status"), "ascii");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TemplateId"), "ascii");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("CampaignId");

                    b.HasIndex("UserEmail", "Status");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.CampaignTemplateEntity", b =>
                {
                    b.Property<string>("TemplateId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TemplateId"), "ascii");

                    b.Property<string>("AllowedTokensJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Category"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DesignJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "ascii");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("TemplateId");

                    b.HasIndex("UserEmail", "Category", "Name");

                    b.ToTable("CampaignTemplates");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.ContactEntity", b =>
                {
                    b.Property<string>("ContactId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactId"), "ascii");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DealValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Email"), "ascii");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EmailNormalized"), "ascii");

                    b.Property<string>("FirstName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("LastName")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("LeadStage")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LeadStage"), "ascii");

                    b.Property<string>("Location")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OwnerEmail"), "ascii");

                    b.Property<string>("ServiceInterest")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Source")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Timezone")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("ContactId");

                    b.HasIndex("UserEmail", "EmailNormalized")
                        .IsUnique();

                    b.HasIndex("UserEmail", "LeadStage");

                    b.HasIndex("UserEmail", "OwnerEmail");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.ContactListEntity", b =>
                {
                    b.Property<string>("ListId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ListId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "ascii");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("ListId");

                    b.HasIndex("UserEmail", "Name");

                    b.ToTable("ContactLists");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.ContactListMemberEntity", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.Property<string>("ListId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ListId"), "ascii");

                    b.Property<string>("ContactId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactId"), "ascii");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserEmail", "ListId", "ContactId");

                    b.ToTable("ContactListMembers");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.CrmNoteEntity", b =>
                {
                    b.Property<string>("NoteId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NoteId"), "ascii");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("NoteId");

                    b.HasIndex("UserEmail", "ContactId", "CreatedAtUtc");

                    b.ToTable("CrmNotes");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.CrmTaskEntity", b =>
                {
                    b.Property<string>("TaskId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TaskId"), "ascii");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DueAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("OwnerEmail"), "ascii");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Priority"), "ascii");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Status"), "ascii");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("TaskId");

                    b.HasIndex("UserEmail", "OwnerEmail", "Status");

                    b.HasIndex("UserEmail", "ContactId", "Status", "DueAtUtc");

                    b.ToTable("CrmTasks");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.EmailClassificationEntity", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MessageId"), "ascii");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserEmail", "MessageId");

                    b.HasIndex("UserEmail");

                    b.ToTable("EmailClassifications");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.JourneyEnrollmentEntity", b =>
                {
                    b.Property<string>("EnrollmentId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EnrollmentId"), "ascii");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("JourneyId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("JourneyId"), "ascii");

                    b.Property<int>("LastProcessedStepOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextRunAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Status"), "ascii");

                    b.Property<string>("TriggerEventId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TriggerEventId"), "ascii");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("UserEmail", "JourneyId", "Status");

                    b.ToTable("JourneyEnrollments");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.JourneyEntity", b =>
                {
                    b.Property<string>("JourneyId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("JourneyId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Status"), "ascii");

                    b.Property<string>("TriggerRefId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TriggerRefId"), "ascii");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TriggerType"), "ascii");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("JourneyId");

                    b.HasIndex("UserEmail", "Status");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.JourneyStepEntity", b =>
                {
                    b.Property<string>("JourneyId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("JourneyId"), "ascii");

                    b.Property<int>("StepOrder")
                        .HasColumnType("int");

                    b.Property<string>("BodyHtmlOverride")
                        .HasColumnType("longtext");

                    b.Property<string>("ConditionEventType")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ConditionEventType"), "ascii");

                    b.Property<int?>("ConditionWindowHours")
                        .HasColumnType("int");

                    b.Property<int>("DelayMinutes")
                        .HasColumnType("int");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("StepType"), "ascii");

                    b.Property<string>("SubjectOverride")
                        .HasColumnType("longtext");

                    b.Property<string>("TemplateId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("TemplateId"), "ascii");

                    b.Property<string>("ToLeadStage")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ToLeadStage"), "ascii");

                    b.HasKey("JourneyId", "StepOrder");

                    b.ToTable("JourneySteps");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.LeadStageHistoryEntity", b =>
                {
                    b.Property<string>("HistoryId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("HistoryId"), "ascii");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EventId"), "ascii");

                    b.Property<string>("EventType")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EventType"), "ascii");

                    b.Property<string>("FromStage")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("FromStage"), "ascii");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ToStage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ToStage"), "ascii");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("HistoryId");

                    b.HasIndex("UserEmail", "ContactId", "CreatedAtUtc");

                    b.ToTable("LeadStageHistory");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.MessageEventEntity", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EventId"), "ascii");

                    b.Property<string>("CampaignId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("CampaignId"), "ascii");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("ContactId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EventType"), "ascii");

                    b.Property<string>("JourneyId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("JourneyId"), "ascii");

                    b.Property<string>("MessageId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("MessageId"), "ascii");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceEventId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SourceEventId"), "ascii");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("EventId");

                    b.HasIndex("UserEmail", "SourceEventId", "EventType");

                    b.HasIndex("UserEmail", "ContactId", "EventType", "OccurredAtUtc");

                    b.ToTable("MessageEvents");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.NotificationEntity", b =>
                {
                    b.Property<string>("NotificationId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NotificationId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Type"), "ascii");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserEmail", "IsRead", "CreatedAtUtc");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.PlatformUpdateEntity", b =>
                {
                    b.Property<string>("UpdateId")
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UpdateId"), "ascii");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Category"), "ascii");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PublishedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("RetrievedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Severity"), "ascii");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Source"), "ascii");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("UpdateId");

                    b.HasIndex("IsActive", "IsCritical", "PublishedAtUtc");

                    b.HasIndex("Source", "Category", "Severity");

                    b.ToTable("PlatformUpdates");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.SegmentEntity", b =>
                {
                    b.Property<string>("SegmentId")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SegmentId"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "ascii");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.HasKey("SegmentId");

                    b.HasIndex("UserEmail", "Name");

                    b.ToTable("Segments");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.SuppressionEntryEntity", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("UserEmail"), "ascii");

                    b.Property<string>("EmailNormalized")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("EmailNormalized"), "ascii");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Email"), "ascii");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("UserEmail", "EmailNormalized");

                    b.ToTable("Suppressions");
                });

            modelBuilder.Entity("GmailManager.Shared.Entities.UserTokenEntity", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("varchar(320)");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Email"), "ascii");

                    b.Property<string>("TokenJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Email");

                    b.ToTable("UserTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
